# Generated by Django 6.0.4 on 2026-04-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_borrowform_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
