# Generated by Django 6.0.4 on 2026-04-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_imageurl_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemimage',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
    ]
