# Generated by Django 6.0.4 on 2026-04-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_itemimage_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowform',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], default='PENDING', max_length=20),
        ),
    ]
